### ISSUE TITLE
Compatible with redmine 2.1.x?

### ISSUE THREAD

**Issue by cforce** [spike008t/redmine_advanced_issues#11]

**Comment by spike008t** [comment]
Yep, the master repository is compatible with the 2.1.x version.

But not compatible with 1.x at the moment.
When I have a moment, i'm gonna port the module on 1.3.x and 1.4.x.

Stay on touch

**Comment by cforce** [comment]
Does not work for redmine 2.1.4 - I can't migrate the plugin

rake aborted!
Hooks is not a module
/home/myuser/DevMine_WK/redmine-2.1.4/plugins/redmine_advanced_issues/lib/hooks/controller_issues_edit_before_save_hook.rb:20:in `(root)'
org/jruby/RubyKernel.java:1019:in`require'
/home/myuser/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
/home/myuser/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in`load_dependency'
/home/myuser/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
/home/myuser/DevMine_WK/redmine-2.1.4/plugins/redmine_advanced_issues/init.rb:1:in`(root)'
org/jruby/RubyKernel.java:1019:in `require'
/home/myuser/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
/home/myuser/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/myuser/.rvm/gems/jruby-1.7.0/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in`require'
/home/myuser/DevMine_WK/redmine-2.1.4/plugins/redmine_advanced_issues/init.rb:86:in `(root)'
org/jruby/RubyArray.java:1612:in`each'
/home/myuser/DevMine_WK/redmine-2.1.4/lib/redmine/plugin.rb:1:in `(root)'
/home/myuser/DevMine_WK/redmine-2.1.4/lib/redmine/plugin.rb:130:in`load'
org/jruby/RubyKernel.java:1045:in `load'

**Comment by cforce** [comment]
Any new here? iT fdoes not work on redmine 2.2.2
