### ISSUE TITLE
Can not be used in redmine 1.3.x

### ISSUE THREAD

**Issue by archonwang** [spike008t/redmine_advanced_issues#4]
when start server. error information:

=> Booting Mongrel
=> Rails 2.3.14 application starting on http://0.0.0.0:3000
NOTE: SourceIndex.new(hash) is deprecated; From C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/r
ails/vendor_gem_source_index.rb:100:in `new'.
E:/redmine-1.3/vendor/plugins/redmine_advanced_issues/lib/hooks/controller_issues_edit_before_save_h
ook.rb:20: Hooks is not a module (TypeError)
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in`gem_original_requir
e'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/dependencies.
rb:184:in`require'
        from E:/redmine-1.3/vendor/plugins/redmine_advanced_issues/init.rb:69:in `evaluate_init_rb'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/rails/plugin.rb:158:in`evaluate_ini
t_rb'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/kern
el/reporting.rb:11:in `silence_warnings'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/rails/plugin.rb:154:in`evaluate_ini
t_rb'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/rails/plugin.rb:48:in `load'
        from E:/redmine-1.3/config/../vendor/plugins/engines/lib/engines/plugin.rb:44:in`load'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/rails/plugin/loader.rb:38:in `load_p
lugins'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/rails/plugin/loader.rb:37:in`each'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/rails/plugin/loader.rb:37:in `load_p
lugins'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/initializer.rb:369:in`load_plugins'

```
    from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/initializer.rb:165:in `process'
    from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/initializer.rb:113:in `send'
    from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/initializer.rb:113:in `run'
    from E:/redmine-1.3/config/environment.rb:24
    from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `gem_original_requir
```

e'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/dependencies.
rb:182:in`require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/dependencies.
rb:547:in `new_constants_in'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/dependencies.
rb:182:in`require'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/rails-2.3.14/lib/commands/server.rb:84
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `gem_original_requir
e'
        from C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in`require'
        from script/server:3

**Comment by spike008t** [comment]
Oups. I'm gonna to check the code. Thank you for the reporting
Le 9 mars 2012 08:40, "Steven.W" <
reply@reply.github.com>
a écrit :

**Comment by ChrisChinchilla** [comment]
I'd be interested to know when this works in 1.3+, just what we're looking for…
