### ISSUE TITLE
Can't use with redmine 1.4.0

### ISSUE THREAD

**Issue by schwinger** [spike008t/redmine_advanced_issues#7]
(Same Post here http://www.redmine.org/issues/6833)
We become error (when we press "new ticket" - or then we open an ticket from the ticketlist)

```
ActionView::TemplateError (uninitialized constant ActionView::Base::CompiledTemplates::TabularFormBuilder) on line #1 of vendor/plugins/redmine_advanced_issues/app/views/issues/_attributes.rhtml:
1: <% fields_for :issue, @issue, :builder => TabularFormBuilder do |f| %>
2: 
3: <div class="splitcontentleft">
4: <% if @issue.new_record? || @allowed_statuses.any? %>

vendor/plugins/redmine_advanced_issues/app/views/issues/_attributes.rhtml:1:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47_attributes46rhtml_locals_attributes_object'
app/views/issues/_form.html.erb:44
app/helpers/application_helper.rb:941:in `labelled_fields_for'
app/views/issues/_form.html.erb:1
vendor/plugins/redmine_advanced_issues/app/views/issues/_edit.rhtml:15:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47_edit46rhtml_locals_edit_object'
app/helpers/application_helper.rb:927:in `labelled_tabular_form_for'
vendor/plugins/redmine_advanced_issues/app/views/issues/_edit.rhtml:1:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47_edit46rhtml_locals_edit_object'
vendor/plugins/redmine_advanced_issues/app/views/issues/show.rhtml:119:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47show46rhtml'
app/controllers/issues_controller.rb:118:in `show'
app/controllers/issues_controller.rb:115:in `show'
thin (1.3.1) lib/thin/connection.rb:80:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:78:in `catch'
thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:53:in `process'
thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
thin (1.3.1) lib/thin/server.rb:159:in `start'
thin (1.3.1) lib/thin/controllers/controller.rb:86:in `start'
thin (1.3.1) lib/thin/runner.rb:185:in `send'
thin (1.3.1) lib/thin/runner.rb:185:in `run_command'
thin (1.3.1) lib/thin/runner.rb:151:in `run!'
thin (1.3.1) bin/thin:6
c:/webserver/ruby/bin/thin:19:in `load'
c:/webserver/ruby/bin/thin:19

Rendering C:/webserver/Redmine/public/500.html (500 Internal Server Error)
```

we insert  tabular_form_builder.rb to ...\Redmine\lib\
from here: http://svn.ohwr.org/ohr-support/trunk/lib/tabular_form_builder.rb
(see http://redminecrm.com/issues/905 or https://github.com/ericpaulbishop/redmine_git_hosting/issues/135)

==> and now "New Ticket" works and we become new Error when we open a ticket from the ticket list.

```
ActionView::TemplateError (undefined method `preview_issue_path' for #<ActionView::Base:0x875b788>) on line #53 of vendor/plugins/redmine_advanced_issues/app/views/issues/_edit.rhtml:
50:     <%= f.hidden_field :lock_version %>
51:     <%= submit_tag l(:button_submit) %>
52:     <%= link_to_remote l(:label_preview), 
53:                        { :url => preview_issue_path(:project_id => @project, :id => @issue),
54:                          :method => 'post',
55:                          :update => 'preview',
56:                          :with => 'Form.serialize("issue-form")',

vendor/plugins/redmine_advanced_issues/app/views/issues/_edit.rhtml:53:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47_edit46rhtml_locals_edit_object'
app/helpers/application_helper.rb:927:in `labelled_tabular_form_for'
vendor/plugins/redmine_advanced_issues/app/views/issues/_edit.rhtml:1:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47_edit46rhtml_locals_edit_object'
vendor/plugins/redmine_advanced_issues/app/views/issues/show.rhtml:119:in `_run_rhtml_vendor47plugins47redmine_advanced_issues47app47views47issues47show46rhtml'
app/controllers/issues_controller.rb:118:in `show'
app/controllers/issues_controller.rb:115:in `show'
thin (1.3.1) lib/thin/connection.rb:80:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:78:in `catch'
thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
thin (1.3.1) lib/thin/connection.rb:53:in `process'
thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
thin (1.3.1) lib/thin/server.rb:159:in `start'
thin (1.3.1) lib/thin/controllers/controller.rb:86:in `start'
thin (1.3.1) lib/thin/runner.rb:185:in `send'
thin (1.3.1) lib/thin/runner.rb:185:in `run_command'
thin (1.3.1) lib/thin/runner.rb:151:in `run!'
thin (1.3.1) bin/thin:6
c:/webserver/ruby/bin/thin:19:in `load'
c:/webserver/ruby/bin/thin:19

Rendering C:/webserver/Redmine/public/500.html (500 Internal Server Error)
```

What can we do ?

Thanks

**Comment by daest** [comment]
I have the same problem. If I open or create a new issue, I allways get an internal error.

**Comment by llsousa** [comment]
Same here :-(
